### ISSUE TITLE
Wireframes maken

### ISSUE THREAD

**Issue by jkalisvaart** [nogohr/escape-room#23]

**Comment by fieg** [comment]
Feedback van @jkalisvaart 
> Nice! Ziet er goed uit. Bij de upselling zou ik wel de prijs erbij zetten. Bij het eerste scherm misschien nog heel basic tekenen hoe de blokken eruit gaan zien waar de escape rooms in komen die geselecteerd kunnen worden.
Verder ziet het er goed uit.

Nog todo:
* [ ]  Bij de upselling zou ik wel de prijs erbij zetten
* [ ] Bij het eerste scherm misschien nog heel basic tekenen hoe de blokken eruit gaan zien waar de escape rooms in komen die geselecteerd kunnen worden.

**Comment by fieg** [comment]
Nieuwe wireframes aan de GDrive toegevoegd.
